// Drizzle schema barrel. Better Auth tables (user/session/account/verification +
// organization/member/invitation + jwks) live in ./auth, generated by
// `npx @better-auth/cli generate` (Unit 09). Domain tables (Unit 10) join here.
export * from "./auth";
