// Drizzle schema barrel. Better Auth tables (user/session/account/verification +
// organization/member/invitation + jwks) live in ./auth, generated by
// `npx @better-auth/cli generate` (Unit 09). Domain tables (Unit 10) live in
// ./domain — every one org-scoped, reached only through repos/.
export * from "./auth";
export * from "./domain";
